{{- range $key, $value := .Values.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $key | trunc 63 | replace "_" "-" | trimSuffix "-" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $value.size }}
---
{{- end }}