apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simple-ssh-bastion.fullname" . }}-ssh-config
data:
  sshd_config: |-
    {{- range $key, $value := .Values.bastion.sshd_config }}
    {{ $key }} {{ $value }}
    {{- end }}